### ISSUE TITLE
All roads should lead to toriel

### ISSUE THREAD

**Issue by maxwofford** [hackclub/toriel#100]
Currently toriel steps in to help users that join through https://hackclub.com/slack.

Toriel does not step in on users who get invited directly to the Slack by members in the Slack (these forms)

<img width="360" alt="Screenshot 2023-01-11 at 11 44 55" src="https://user-images.githubusercontent.com/5891442/211865763-a25f07c3-ef9c-4251-b223-b0b500e936a8.png">
<img width="666" alt="Screenshot 2023-01-11 at 11 45 06" src="https://user-images.githubusercontent.com/5891442/211865778-c08cd1dd-f923-479d-a4ff-feede8492444.png">

This causes confusion because Clippy steps in for those joiners and they get stuck.

**Comment by tregsthedev** [comment]
I think this was fixed by a commit Sam made a while ago
