### ISSUE TITLE
Implement evergreen channels with the activte channel checker

### ISSUE THREAD

**Issue by tregsthedev** [hackclub/toriel#157]
This would recommend some channels for people In the slack that they can check out and have fun with. Evergreen channels are channels that don't change much like XKCD, 8ball, WHACK A MOLE, etc

**Comment by VelocityDesign** [comment]
How are we thinking about implementing this? By using something like keywords, e.g. if the join message mentions linux, recommend #linux?

**Comment by tregsthedev** [comment]
There's a file here that Max pushed a while ago that checks recent channel activity the idea is to recommend one if those that had a message recently in the allowlist

**Comment by tregsthedev** [comment]
I'm trying to find the file one sec

**Comment by tregsthedev** [comment]
https://github.com/hackclub/toriel/blob/main/util%2Fchannel-is-active.js

**Comment by karamassie** [comment]
i believe we decided to go with a shortlist of very active channels instaed. suggest closing.
