### ISSUE TITLE
Only notify welcome committee when user should actually be welcomed

### ISSUE THREAD

**Issue by tregsthedev** [hackclub/toriel#158]

**Comment by yednapg** [comment]
- Even if a person fills TORIEL again, it should not show up in #welcome-committee
- Speaking for people who welcome others - TORIEL should post messages only for those who have joined Slack for the first time

**Comment by jdogcoder** [comment]
Yea +1 on what @yednapg said. 

@tregsthedev, what's the status of this?

**Comment by grymmy** [comment]
seems trivial to add a conditional here checking the DB state -  https://github.com/hackclub/toriel/blob/02bb7120a0bc5bcf8657d9aa23322c50cb175313/interactions/post-welcome-committee.js#L18C5-L18C5

**Comment by maxwofford** [comment]
Should be addressed by https://github.com/hackclub/toriel/commit/f16dbc0b767df5c2b356c52cd4f5c4b10888d6ef, will close after testing

**Comment by maxwofford** [comment]
Original commit was fixed in https://github.com/hackclub/toriel/commit/d44aa63b33b4885210589c36946e32a561bdaf83 & works in prod!
