### ISSUE TITLE
Invited to slack-themes while still in cave channel

### ISSUE THREAD

**Issue by maxwofford** [hackclub/toriel#16]
This one is hard to explain, so I've attached a movie below. Basically, calling for help in the cave channel will trigger a DM, but the DM flow invites the user to the slack-themes channel. We want to only invite a user to slack-themes after we know they're in DMs, so we probably only want to invite theme to slack-themes after a button press or something.

https://user-images.githubusercontent.com/5891442/162321844-a281d576-6ecd-4b27-b710-64a9252a7fc2.mov

**Comment by tregsthedev** [comment]
closing, because this is no longer happening
