### ISSUE TITLE
Onboarding stuck on tutorial

### ISSUE THREAD

**Issue by Adimac93** [hackclub/toriel#163]
I've recently joined the Hack Club community but I am unable to proceed with the tutorial. Toriel redirects me to a private channel after `/toriel-restart`.

![image](https://github.com/hackclub/toriel/assets/47300834/b401c7f5-b885-4e67-80db-1294aeb14f3a)

**Comment by tregsthedev** [comment]
Hi Adam! We're currently fixing a small issue related to this! Thanks for
the report, what's your slack username so I can reset you? On Tue, Aug 29,
2023, 6:45 am Adam Maciejczuk
