### ISSUE TITLE
Toriel doesn't say goodbye!

### ISSUE THREAD

**Issue by maxwofford** [hackclub/toriel#17]
<img width="470" alt="Screen Shot 2022-04-07 at 17 20 47" src="https://user-images.githubusercontent.com/5891442/162316853-658329e8-9eaa-4c92-8ebc-fc82fda7c4d9.png">

Currently when you finish the toriel flow & click the final button to be upgraded to a full user, it just says "You left TORIEL's house and stepped in to town...". It'd be awesome if we included more details there for people who come back later and check out their DM's. Some thoughts about what could be included:

- Instructions on using the `/toriel-call` command (could flavor it like "you're going out into the Slack town, but if you ever want to reach me back at my house run this command" or something else creative)
- Link to Toriel's codebase– make it feel open-source and editable
- Other recommended slack channels(?)
- An easter-egg (b/c users who get promoted will end up in the announcements channel after their slack client updates, so only inquisitive users will end up seeing the DM)

**Comment by tregsthedev** [comment]
Can I be assigned to this please?

**Comment by karamassie** [comment]
flow has been changed so this isn't relevant.
