### ISSUE TITLE
Handle users joining through `/invite` flow

### ISSUE THREAD

**Issue by maxwofford** [hackclub/toriel#187]
Currently the Toriel flow assumes users are joining through hackclub.com/slack, which includes a bunch of handy-dandy fields like `join_reason` & `country` that she references. Not all Slack users join through that form though and bad things can happen (such as marking the user as running `/toriel-restart`).

Let's actually have a flow for users just getting invited directly through `/invite`

**Comment by jdogcoder** [comment]
![CleanShot 2024-02-01 at 12 14 50@2x](https://github.com/hackclub/toriel/assets/65788728/a0f6abfe-485c-40e7-94b5-28d54c5a4fbe)
Important reference for whoever takes this
