### ISSUE TITLE
Onboard flow: guest default channel name doesn't quite work in email format

### ISSUE THREAD

**Issue by karamassie** [hackclub/toriel#189]
The Slack email invite looks like this:

<img width="622" alt="Screenshot 2024-01-17 at 11 32 50 AM" src="https://github.com/hackclub/toriel/assets/99233707/1d7aae68-bbf3-4f76-96ba-00b4454aebae">

"click me to start" is a bit awkward and doesn't have the same aura as the rest of the onboarding. 

I suggest "#cave-entrance-START-HERE"

**Comment by maxwofford** [comment]
<img width="525" alt="Screenshot 2024-01-18 at 16 20 38" src="https://github.com/hackclub/toriel/assets/5891442/44d0930c-b434-4d68-ba48-42e1226cb1c1">

The channel name has now been updated to `#cave-entrance`! It should also be noted the channel description still says "cry for help", when that button was relabeled to "start".

**Comment by maxwofford** [comment]
<img width="679" alt="Screenshot 2024-01-18 at 16 23 07" src="https://github.com/hackclub/toriel/assets/5891442/027e4d3f-ba63-4e28-8f98-030af40e2686">

Here's what the invite looks like now
