### ISSUE TITLE
onboarding flow: text change for clarity

### ISSUE THREAD

**Issue by karamassie** [hackclub/toriel#191]
current screenshot of flow:
<img width="658" alt="Screenshot 2024-01-17 at 11 45 32 AM" src="https://github.com/hackclub/toriel/assets/99233707/b3c61f82-b7c2-4f7b-8556-ad7ecf4a63e5">

1. amend to suggested text for clarity and context
2. the 1 symbol in the text is red right now. in slack it is actually purple, so please make purple.

Hi! I’m Toriel. You must be new ‘round here! Let me show you a couple of things. I have tea and butterscotch pie too!

I sent you a DM (direct message). You can tell by the (1) to the left. Open it!

**Comment by maxwofford** [comment]
@karamassie it's purple for you because you customized your Slack's theme! On a new account it's red
