### ISSUE TITLE
onboarding flow: remove step telling people to fill out profile

### ISSUE THREAD

**Issue by karamassie** [hackclub/toriel#192]
while this is super useful later, it's just more friction in the onboarding PLUS right now our screenshot is out of date, so this is confusing ah. let's remove this step!

screenshot of step to remove (all of this please)
<img width="613" alt="Screenshot 2024-01-17 at 11 48 51 AM" src="https://github.com/hackclub/toriel/assets/99233707/fec2885d-0e10-4f08-91bd-8abd38017aec">

**Comment by maxwofford** [comment]
Removed! https://github.com/hackclub/toriel/commit/37e2efcf83f17b56bd97e7a368a2f802a0c6789a
