### ISSUE TITLE
during onboarding asking people if they are a club leader isn't doing anything

### ISSUE THREAD

**Issue by karamassie** [hackclub/toriel#193]
1. suggest we remove it until it's fixed

fixes include

a) having a note in #welcome-committee that theyre a club leader
b) adding them to #leaders as one of their default channels AND
c) having #leaders on the suggested list later in the flow

**Comment by maxwofford** [comment]
It now invites! Fixed in https://github.com/hackclub/toriel/commit/a0550ae58f7a2111c79d5fe8933c67674029c9db & https://github.com/hackclub/toriel/commit/4954153e85732e34c74217cd5d88c08bea6ead05
