### ISSUE TITLE
/toriel-restart resets user join reason

### ISSUE THREAD

**Issue by jaspermayone** [hackclub/toriel#236]
Is there some way of preserving a user's original join reason?

**Comment by aboutdavid** [comment]
It appears to be the same after restarting, even when testing in prod

**Comment by jaspermayone** [comment]
super weird

**Comment by jaspermayone** [comment]
@aboutdavid in the welcome committee, where do users get that msg from? we shouldnt have any case for that anymore

**Comment by aboutdavid** [comment]
> @aboutdavid in the welcome committee, where do users get that msg from? we shouldnt have any case for that anymore

I... don't exactly know...

**Comment by jaspermayone** [comment]
That would probably be the next step here then :)
