### ISSUE TITLE
Implement CI & Unit Testing

### ISSUE THREAD

**Issue by jaspermayone** [hackclub/toriel#239]
Implement proper UI & Unit Testing to allow for better testing of PR's and accountability.

**Comment by jaspermayone** [comment]
CI is also currently failing which is also an issue.

**Comment by tregsthedev** [comment]
CI fails because of formatting

**Comment by jaspermayone** [comment]
Yea I am aware.

**Comment by jaspermayone** [comment]
we want proper ci and unit testing tho
