### ISSUE TITLE
Fully Grafanaify Toriel

### ISSUE THREAD

**Issue by jaspermayone** [hackclub/toriel#257]
Currently we have basic metrics for toriel, but we need to go really crazy in order to get the right alerting and things to make sure toriel is functioning properly.

**Comment by jaspermayone** [comment]
See @grymmy's input here:

![CleanShot 2024-05-24 at 11 55 26@2x](https://github.com/hackclub/toriel/assets/65788728/bd0205b7-cd24-42b5-8c97-1499451ee161)

**Comment by jaspermayone** [comment]
My hard requirements are very simple. When toriel has a heart attack, send me a text or call me alerting me so I can properly sort through what is broken and fix or assign people to fix.

**Comment by aboutdavid** [comment]
Like an automated text message?

**Comment by jaspermayone** [comment]
Yep.

**Comment by jaspermayone** [comment]
I have a Twillio Act I can share creds for

**Comment by aboutdavid** [comment]
Alright, can you send them?

**Comment by jaspermayone** [comment]
Sent!
