### ISSUE TITLE
Handle "invites" when someone is already in the slack

### ISSUE THREAD

**Issue by jaspermayone** [hackclub/toriel#262]
Recently we had a user complain they weren't receiving invites to the slack. Turns out they had already received one, and so it doesn't send a new one.

We should find a way for Toriel to alert a user (or mb it's on the hackclub.com/site page) when this is the case, to eliminate confusion.

CC: @tregsthedev who caught this!

**Comment by tregsthedev** [comment]
We should have it send a email if someone is already in the database or
alert us somewhere in #welcome-committee maybe?

**Comment by jaspermayone** [comment]
I think it should email them and CC slack@ or one of us

**Comment by jaspermayone** [comment]
Welcome Committee should only be for welcomes

**Comment by jaspermayone** [comment]
if we want it on slack we can add an additional channel

**Comment by radioblahaj** [comment]
Closing this until Toriel is being used again
