### ISSUE TITLE
Count dracula DM on user upgrade

### ISSUE THREAD

**Issue by maxwofford** [hackclub/toriel#27]
<img width="708" alt="Screen Shot 2022-04-11 at 16 36 42" src="https://user-images.githubusercontent.com/5891442/162827619-bb3db6af-2605-44a0-a71e-e3adab342511.png">

**Comment by maxwofford** [comment]
One fix for this might be to have toriel give a couple recommendations for what to join when someone becomes a full user, rather than automatically adding people to channels.

**Comment by tregsthedev** [comment]
Closing this, because I don't think it does this anymore
