### ISSUE TITLE
Rotate all API keys after Heroku security breach

### ISSUE THREAD

**Issue by maxwofford** [hackclub/toriel#45]
Part of https://github.com/hackclub/hackclub/issues/1767

These tokens need to be rotated:

- [ ] SLACK_SIGNING_SECRET
- [ ] SLACK_BOT_TOKEN
- [ ] SLACK_LEGACY_TOKEN
- [ ] SLACK_INVITE_TOKEN
- [x] AUTH_TOKEN (& also changed in hackclub/site)
- [ ] DATABASE_URL

**Comment by exu3** [comment]
Would any of these tokens also happen to be used in hackclub/site for the Slack invite service?

**Comment by maxwofford** [comment]
@exu3 I believe they are, could you look that up and help update the description? I'd love to make sure that we don't take down other stuff when rotating these keys.

**Comment by exu3** [comment]
I don't have write-access on the repo, so I can't update the description, but the following tokens will need to be updated on hackclub/site (Vercel) once they're updated here.

AUTH_TOKEN (named TORIEL_KEY in hackclub/site)
SLACK_LEGACY_TOKEN[^1]

[^1]: side note: can these even still be regenerated?

**Comment by maxwofford** [comment]
@exu3 you should have access now! Would you mind setting that up in hackclub/site & hackclub/toriel at the same time to minimize downtime? Feel free to set that the auth token any password you want!

**Comment by exu3** [comment]
AUTH_TOKEN / TORIEL_KEY should be good now! I have tested to verify it works in production.
