### ISSUE TITLE
Rewrite Toriel signup flow

### ISSUE THREAD

**Issue by cosmicoptima** [hackclub/toriel#61]
- [x] stylistic changes to #in-the-cave posts
- [x] remove slack theming section
- [x] rewrite code of conduct section
- [x] remove "are you really sure you want to continue"
- [x] remove "done" posts
- [x] add "fill out profile" section
- [x] add "are you a club leader" section (+ dm holly)
- [x] dump user into different channels
- [x] add "what to do in channels" section

# before
## in #in-the-cave
![image](https://user-images.githubusercontent.com/80304394/179852626-7f0cbfa8-3490-4a59-89af-683eca614b17.png)
![image](https://user-images.githubusercontent.com/80304394/179852671-f7975441-7191-45fd-9275-0c6d3cd3d5ad.png)
## in dms
![image](https://user-images.githubusercontent.com/80304394/179852726-f2e1bdb0-ac18-4490-b86b-2ba560533070.png)
![image](https://user-images.githubusercontent.com/80304394/179852749-faef77b1-80c5-4883-8bf1-6ec76b8f8a02.png)
![image](https://user-images.githubusercontent.com/80304394/179852759-a4e03800-9016-42e7-b198-f82adb4ef27a.png)
![image](https://user-images.githubusercontent.com/80304394/179852775-8eedaed1-868b-409e-a33f-69551c079adb.png)
(user is put into #announcements, #code, #confessions, #hack-night, #hq, #lounge, #neighbourhood, #pasture, #poll-of-the-day, #question-of-the-day, #scrapbook, #ship)

# after
## in #in-the-cave
![image](https://user-images.githubusercontent.com/80304394/179852843-b7a7e3bf-f5db-462d-89cb-81da4505bb90.png)
![image](https://user-images.githubusercontent.com/80304394/179852863-6dc1e2fb-20f6-4e0e-9eee-16a8025c5b2c.png)
## in dms
![image](https://user-images.githubusercontent.com/80304394/179852884-a368bcef-cccc-4a45-b295-565100513df9.png)
![image](https://user-images.githubusercontent.com/80304394/179852907-a5af51a0-3e09-4575-aa25-75acf16359a1.png)
![image](https://user-images.githubusercontent.com/80304394/179852924-b0c51bae-7d55-4000-aaad-52687518eda5.png)
(if yes, send to holly:)
![image](https://user-images.githubusercontent.com/80304394/179852979-cd148099-901a-4918-9e82-0683132b928e.png)
(user is put into #lounge, #ship, #scrapbook, #leaders IF club leader, #announcements, #hq, #neighbourhood, #8-ball, #code, #confessions, #counttoamillion, #hack-night, #question-of-the-day)
![image](https://user-images.githubusercontent.com/80304394/179853304-2e99251f-2230-45d0-90ec-baf230a011c2.png)
(possible suggestions are:)
<img width="576" alt="Screen Shot 2022-07-19 at 17 40 20" src="https://user-images.githubusercontent.com/80304394/179853332-1d9fe39b-98f5-4f4d-87cd-8a83fb8e9e9a.png">

**Comment by karamassie** [comment]
this looks done @maxwofford
