### ISSUE TITLE
Code of conduct feels like a wall of text

### ISSUE THREAD

**Issue by maxwofford** [hackclub/toriel#9]
This is what Toriel's Code of Conduct steps looks like currently:

<img width="561" alt="Screen Shot 2022-04-07 at 17 05 38" src="https://user-images.githubusercontent.com/5891442/162307999-0c100501-45ad-4956-9b31-122b05685b46.png">

It's kinda a wall of text. Maybe we can break it down with bulletpoints and bolding the important parts? Also, we're in the Slack, so instead of "email conduct@hackclub.com", maybe it could be "run /report" or something?

**Comment by karamassie** [comment]
+1 on this. here's my suggested copy (in the FLOW doc, too):

**Toriel**
Friend, please enjoy the tea and pie while you read this. 

They point to a page in a book in front of you. “The Tenants of the Hack Club Slack (abridged 14th ed.), Orpheus et al.

[READ ME](url=https://hackclub.com/conduct)

Handwritten in the margins, it says 
_Be kind, thoughtful and no advertisements._

Toriel leans in. "Do you vow to uphold the hacker values?"

[I DO]

**Comment by maxwofford** [comment]
Shortened in https://github.com/hackclub/toriel/commit/37e2efcf83f17b56bd97e7a368a2f802a0c6789a!
