### ISSUE TITLE
Ask about hackcathons.hackclub.com notifications

### ISSUE THREAD

**Issue by YodaLightsabr** [hackclub/toriel#90]
Add a step to the onboarding flow for adding your email to the hackathons.hackclub.com list

**Comment by ajs256** [comment]
What if after the "and with that" message, you (the user) saw a message that said something like
> one more thing. we really love hackathons here, and we want to see you at one. do you want us to email you when there's a new one in your area?

Toriel already has the new member's email, we should be able to pop a form to ask for their location. @YodaLightsabr does hackathons.hc.com have an API?

**Comment by northeastprince** [comment]
Yes, [that's how users signups are communicated](https://github.com/hackclub/hackathons/blob/315fa1afb4aa6354c119ff1ea3b846bd79c4793f/components/signup.js#L42).

**Comment by karamassie** [comment]
not doing this

**Comment by karamassie** [comment]
this sounds like we're asking to send spam PLUS people are already finding the current flow long. let's discuss in DMs in Slack what you're trying to accomplish and how better to do it!
